{% set name = "smqtk-detection" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smqtk_detection-{{ version }}.tar.gz
  sha256: 089030d58dfb57ae0d0d8f6c4e6fab316da6973f6d7ab4e7f8655297bf6ef0e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - smqtk-core >=0.20.0
    - smqtk-classifier >=0.20.0
    - smqtk-dataprovider >=0.19.0
    - smqtk-image-io >=0.18.0

test:
  imports:
    - smqtk_detection
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kitware/SMQTK-Detection
  summary: Algorithms, data structures and utilities around performing detection of inputs
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Purg
    - barry-ravichandran
